interfaces:
  management: wlan0
  monitor: wlan1
filters:
  whitelist:
    - "^TP-Link_.*"
  blacklist:
    - "^TP-Link_.*SN.*$"
    - '^12345678\+$'
    - "^TP-Link_40C5.*$"
    - "^TP-Link_98AC.*$"
capture:
  handshake_timeout: 3600
  revisit_interval: 300
  verify: true
paths:
  captures: captures
  hashes: hashes
  reports: reports
  logs: logs
  state: state/state.json
cracking:
  hashcat: hashcat
  mask: "?d?d?d?d?d?d?d?d"
logging:
  level: INFO
